title: "Kode With Klossy Curriculum"
description: "Open source curriculum for the Kode With Klossy's 2020 WebDev and Mobile camps."
url: "https://turingschool.github.io/kwk-curriculum-site"

baseurl: ''
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/kwk-curriculum-site/assets'

images:
  root_url: '/kwk-curriculum-site/assets/images'

plugins:
  - jemoji
